baseURL = 'https://notes.flwgns.ovh/'
languageCode = 'en-us'
title = 'Notes'

theme = 'PaperMod'

copyright = '''
[Source code](https://github.com/flowgunso/blog) is under [MIT license](https://github.com/flowgunso/blog/blob/main/LICENSE),
[articles](https://github.com/flowgunso/blog/tree/main/content) are under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
'''

[outputs]
home = [ 'HTML', 'RSS', 'JSON' ]

[[menu.main]]
name = "Search"
url = "search"
weight = 5

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Tags"
url = "tags"
weight = 10

[params.homeInfoParams]
Title = 'Notes'
Content = 'About the stuff I do.' 

[[params.socialIcons]]
name = "Docker"
title = "Docker Hub"
url = "https://hub.docker.com/r/flrnnc"

[[params.socialIcons]]
name = "gitlab"
title = "Gitlab"
url = "https://gitlab.com/florian.anceau"

[[params.socialIcons]]
name = "Liberapay"
title = "Support my work"
url = "https://liberapay.com/florian.anceau"

[[params.socialIcons]]
name = "BuyMeACoffee"
title = "Buy me a coffee"
url = "https://buymeacoffee.com/florian.anceau"

[[params.socialIcons]]
name = "github"
title = "Github"
url = "https://github.com/flowgunso"
